---
name: Lint Bash Script

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Log Git Reference Info
        run: |
          cat << EOF
          GITHUB_REF:       ${GITHUB_REF}
          GITHUB_REF_TYPE:  ${GITHUB_REF_TYPE}
          GITHUB_REF_NAME:  ${GITHUB_REF_NAME}
          EOF
      - name: Set up Python
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y software-properties-common jq make
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get install --no-install-recommends -y python${PYTHON_VERSION} python${PYTHON_VERSION}-venv python3-pip
      - name: Lint everything
        run: make lint
